export const BASE_URL = 'http://localhost:5003'
export const USERS_URL = '/api/user'
export const CATEGORIES_URL = '/api/category'
export const PRODUCT_URL = '/api/product'
export const UPLOAD_URL = '/api/upload'
